---
ingress:
  frontend:
    hosts:
      - stage.aqua-pump.net
  backend:
    host: api-stage.aqua-pump.net

backend:
  existingSecret: aquapump-secrets

frontend:
  existingSecret: aquapump-secrets
